baseURL = '/'
languageCode = 'en-us'
title = 'Undersea Transmissions Archive'
theme = "blank-local"
contentDir = "content"
relativeURLs = true

[markup.goldmark.renderer]
unsafe = true

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
      [markup.goldmark.parser.attribute]
        block = true